// Generated by gencpp from file ros_unity_msgs/PosData.msg
// DO NOT EDIT!


#ifndef ROS_UNITY_MSGS_MESSAGE_POSDATA_H
#define ROS_UNITY_MSGS_MESSAGE_POSDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_unity_msgs
{
template <class ContainerAllocator>
struct PosData_
{
  typedef PosData_<ContainerAllocator> Type;

  PosData_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  PosData_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::ros_unity_msgs::PosData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_unity_msgs::PosData_<ContainerAllocator> const> ConstPtr;

}; // struct PosData_

typedef ::ros_unity_msgs::PosData_<std::allocator<void> > PosData;

typedef boost::shared_ptr< ::ros_unity_msgs::PosData > PosDataPtr;
typedef boost::shared_ptr< ::ros_unity_msgs::PosData const> PosDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_unity_msgs::PosData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_unity_msgs::PosData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_unity_msgs::PosData_<ContainerAllocator1> & lhs, const ::ros_unity_msgs::PosData_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_unity_msgs::PosData_<ContainerAllocator1> & lhs, const ::ros_unity_msgs::PosData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_unity_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_unity_msgs::PosData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_unity_msgs::PosData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_unity_msgs::PosData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_unity_msgs::PosData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_unity_msgs::PosData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_unity_msgs::PosData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_unity_msgs::PosData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47802147045815b06859cca542c21d31";
  }

  static const char* value(const ::ros_unity_msgs::PosData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47802147045815b0ULL;
  static const uint64_t static_value2 = 0x6859cca542c21d31ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_unity_msgs::PosData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_unity_msgs/PosData";
  }

  static const char* value(const ::ros_unity_msgs::PosData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_unity_msgs::PosData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::ros_unity_msgs::PosData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_unity_msgs::PosData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_unity_msgs::PosData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_unity_msgs::PosData_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_UNITY_MSGS_MESSAGE_POSDATA_H
