// Generated by gencpp from file ros_tcp_endpoint/UnityHandshake.msg
// DO NOT EDIT!


#ifndef ROS_TCP_ENDPOINT_MESSAGE_UNITYHANDSHAKE_H
#define ROS_TCP_ENDPOINT_MESSAGE_UNITYHANDSHAKE_H

#include <ros/service_traits.h>


#include <ros_tcp_endpoint/UnityHandshakeRequest.h>
#include <ros_tcp_endpoint/UnityHandshakeResponse.h>


namespace ros_tcp_endpoint
{

struct UnityHandshake
{

typedef UnityHandshakeRequest Request;
typedef UnityHandshakeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UnityHandshake
} // namespace ros_tcp_endpoint


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_tcp_endpoint::UnityHandshake > {
  static const char* value()
  {
    return "d618401021d6663c32eb0d5da40be68e";
  }

  static const char* value(const ::ros_tcp_endpoint::UnityHandshake&) { return value(); }
};

template<>
struct DataType< ::ros_tcp_endpoint::UnityHandshake > {
  static const char* value()
  {
    return "ros_tcp_endpoint/UnityHandshake";
  }

  static const char* value(const ::ros_tcp_endpoint::UnityHandshake&) { return value(); }
};


// service_traits::MD5Sum< ::ros_tcp_endpoint::UnityHandshakeRequest> should match
// service_traits::MD5Sum< ::ros_tcp_endpoint::UnityHandshake >
template<>
struct MD5Sum< ::ros_tcp_endpoint::UnityHandshakeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tcp_endpoint::UnityHandshake >::value();
  }
  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tcp_endpoint::UnityHandshakeRequest> should match
// service_traits::DataType< ::ros_tcp_endpoint::UnityHandshake >
template<>
struct DataType< ::ros_tcp_endpoint::UnityHandshakeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_tcp_endpoint::UnityHandshake >::value();
  }
  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_tcp_endpoint::UnityHandshakeResponse> should match
// service_traits::MD5Sum< ::ros_tcp_endpoint::UnityHandshake >
template<>
struct MD5Sum< ::ros_tcp_endpoint::UnityHandshakeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tcp_endpoint::UnityHandshake >::value();
  }
  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tcp_endpoint::UnityHandshakeResponse> should match
// service_traits::DataType< ::ros_tcp_endpoint::UnityHandshake >
template<>
struct DataType< ::ros_tcp_endpoint::UnityHandshakeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_tcp_endpoint::UnityHandshake >::value();
  }
  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TCP_ENDPOINT_MESSAGE_UNITYHANDSHAKE_H
