// Generated by gencpp from file ros_tcp_endpoint/UnityHandshakeResponse.msg
// DO NOT EDIT!


#ifndef ROS_TCP_ENDPOINT_MESSAGE_UNITYHANDSHAKERESPONSE_H
#define ROS_TCP_ENDPOINT_MESSAGE_UNITYHANDSHAKERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tcp_endpoint
{
template <class ContainerAllocator>
struct UnityHandshakeResponse_
{
  typedef UnityHandshakeResponse_<ContainerAllocator> Type;

  UnityHandshakeResponse_()
    : ip()  {
    }
  UnityHandshakeResponse_(const ContainerAllocator& _alloc)
    : ip(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ip_type;
  _ip_type ip;





  typedef boost::shared_ptr< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UnityHandshakeResponse_

typedef ::ros_tcp_endpoint::UnityHandshakeResponse_<std::allocator<void> > UnityHandshakeResponse;

typedef boost::shared_ptr< ::ros_tcp_endpoint::UnityHandshakeResponse > UnityHandshakeResponsePtr;
typedef boost::shared_ptr< ::ros_tcp_endpoint::UnityHandshakeResponse const> UnityHandshakeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator1> & lhs, const ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ip == rhs.ip;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator1> & lhs, const ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tcp_endpoint

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e9f1bacbbf36194990498b0461c2f3b";
  }

  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e9f1bacbbf36194ULL;
  static const uint64_t static_value2 = 0x990498b0461c2f3bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tcp_endpoint/UnityHandshakeResponse";
  }

  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ip\n"
;
  }

  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UnityHandshakeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tcp_endpoint::UnityHandshakeResponse_<ContainerAllocator>& v)
  {
    s << indent << "ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TCP_ENDPOINT_MESSAGE_UNITYHANDSHAKERESPONSE_H
