alias src="source /opt/ros/noetic/setup.bash && source /workspace/catkin_ws/devel/setup.bash"
alias src2="source /opt/ros/foxy/setup.bash && source install/setup.bash"

alias cws2="cd /workspace/colcon_ws"
alias bws2="source /opt/ros/foxy/setup.bash && cws2 && colcon build --symlink-install && src2"

alias cws="cd /workspace/catkin_ws"
alias bws="source /opt/ros/noetic/setup.bash && cws && catkin build && src"

alias cbws="cd /workspace/bridge_ws"
alias bbws="cbws && source /workspace/catkin_ws/devel/setup.bash && source /workspace/colcon_ws/install/setup.bash && colcon build --symlink-install --packages-select ros1_bridge --cmake-force-configure && src2"

alias killgazebo="pkill -9 gazebo & pkill -9 gzserver & pkill -9 gzclient & pkill -9 gazebo_gui"